config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
lombok.log.custom.declaration = com.xxx.yyy.zzz.core.logging.Logger com.xxx.yyy.zzz.core.logging.LoggerFactory.getLogger(TYPE,TOPIC)